# Generated by Django 3.2 on 2021-04-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonewspaper', '0002_auto_20210423_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
