# Generated by Django 3.2 on 2021-04-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangonewspaper', '0005_auto_20210423_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
